from FreeBodyEngine.core.node import Node3D
from FreeBodyEngine.graphics.mesh import Mesh
from FreeBodyEngine.graphics.material import Material
from FreeBodyEngine.math import Vector3

class Model:
    def __init__(self, meshes: dict[str, Mesh], material_map: dict[str, str], materials: dict[str, Material]):
        self.meshes: dict[str, Mesh] = meshes
        self.material_map: dict[str, str] = material_map
        self.materials: dict[str, Material] = materials
        
        self.animations = None
        self.skeleton = None

    def to_data(self) -> dict:
        pass

    @classmethod
    def from_data(self) -> 'Model':
        '''Creates a model object from the data generated by the "to_data" function. '''
        pass


class Model3D(Node3D):
    def __init__(self, model: Model, position: Vector3 = Vector3(), rotation: Vector3 = Vector3(), scale: Vector3 = Vector3(1, 1, 1)):
        super().__init__(position, rotation, scale)

        self._model = model
