"""Packs a font's glyphs (generated by font/msdfgen.py) into one MSDF atlas
texture + a `.fbfont` sidecar, using the engine's existing shelf-based
AtlasGen packer (build/atlas_gen.py) - the same packer the release asset
build uses for regular sprites - instead of the previous fixed-grid, no-
padding layout, which wasted space and let adjacent glyphs bleed into each
other under linear filtering.
"""
import freetype

from FreeBodyEngine.font.msdfgen import generate_char, get_global_metadata
from FreeBodyEngine.build.atlas_gen import AtlasGen

GLYPH_PADDING = 2  # transparent gutter per glyph, in output texels - avoids
                    # linear-filter bleed between adjacent atlas cells.


def generate_atlas(path_or_stream, size: int, atlas_size: int = 512, range_px: float = 4.0):
    """Returns (atlas_image: PIL.Image, metadata: dict) for every printable
    ASCII glyph in the font at `path_or_stream`. `metadata` follows the
    msdf-atlas-gen-compatible schema documented in build's Part 3 plan:
    `{"atlas": {...}, "metrics": {...}, "glyphs": [...]}`.
    """
    face = freetype.Face(path_or_stream)
    face.set_char_size(size * 64)

    ascender, descender, line_height = get_global_metadata(face, size)

    printable_chars = [chr(i) for i in range(32, 127) if face.get_char_index(i) != 0 and chr(i) != " "]

    padded_images: dict[str, "Image.Image"] = {}
    glyph_meta: dict[str, dict] = {}

    for char in printable_chars:
        img, char_meta = generate_char(char, face, size, range_px=range_px)
        padded = _pad(img, GLYPH_PADDING)
        padded_images[char] = padded
        glyph_meta[char] = char_meta

    packer = AtlasGen(images=padded_images, atlas_size=atlas_size)
    atlas = packer.build_atlas()

    glyphs = []
    for char in printable_chars:
        nx, ny, nw, nh = packer.positions[char]
        atlas_w, atlas_h = packer.atlas_size, packer.atlas_size
        # Subtract the padding back out so the gutter added purely to avoid
        # filter bleed never leaks into the UVs a consumer actually samples.
        px, py = nx * atlas_w, ny * atlas_h
        pw, ph = nw * atlas_w, nh * atlas_h
        left = px + GLYPH_PADDING
        top = py + GLYPH_PADDING
        right = px + pw - GLYPH_PADDING
        bottom = py + ph - GLYPH_PADDING

        glyphs.append({
            "unicode": ord(char),
            "advance": glyph_meta[char]["advance"],
            "planeBounds": glyph_meta[char]["planeBounds"],
            "atlasBounds": {"left": left, "bottom": bottom, "right": right, "top": top},
        })

    # A space still needs an advance-only entry (no visual bitmap).
    if face.get_char_index(ord(" ")) != 0:
        face.load_char(" ", freetype.FT_LOAD_NO_BITMAP | freetype.FT_LOAD_NO_SCALE)
        space_advance = face.glyph.advance.x / face.units_per_EM
        glyphs.append({
            "unicode": 32,
            "advance": space_advance,
            "planeBounds": {"left": 0.0, "bottom": 0.0, "right": 0.0, "top": 0.0},
            "atlasBounds": {"left": 0.0, "bottom": 0.0, "right": 0.0, "top": 0.0},
        })

    metadata = {
        "atlas": {
            "type": "msdf",
            "distanceRange": range_px,
            "size": size,
            "width": packer.atlas_size,
            "height": packer.atlas_size,
        },
        "metrics": {
            "ascender": ascender,
            "descender": descender,
            "lineHeight": line_height,
            "emSize": 1.0,
        },
        "glyphs": glyphs,
    }

    return atlas, metadata


def _pad(img, padding: int):
    from PIL import Image
    if padding <= 0:
        return img
    w, h = img.size
    padded = Image.new("RGBA", (w + 2 * padding, h + 2 * padding), (0, 0, 0, 0))
    padded.paste(img, (padding, padding))
    return padded
